<dependency>
    <groupId>dev.arbjerg</groupId>
    <artifactId>lavaplayer</artifactId>
    <version>2.1.0</version>

    <exclusions>
        <exclusion>
            <groupId>com.github.walkyst</groupId>
            <artifactId>JAADec-fork</artifactId>
        </exclusion>
    </exclusions>
</dependency>

<!-- JAADec correto -->
<dependency>
    <groupId>com.github.walkyst.JAADec-fork</groupId>
    <artifactId>jaadec-ext-aac</artifactId>
    <version>0.1.3</version>
</dependency>